### ISSUE TITLE
Plugin crashes the debugger upon exit

### ISSUE THREAD

**Issue by prolium** [phiDelPark/x64DbgPlugins#1]
Hello, first of all thanks a lot for this plugin, its simple GUI makes things easier when managing comments and labels.
There's a currently a bug that makes x64dbg crash when you exit it.
- Steps to reproduce:
1- Install the plugin and open the 32-bit or the 64-bit version of the debugger
2- Simply close the debugger and it will crash
- Tested on debugger version **Mar 10 2019, 00:50:10** [(snapshot_2019-03-10_00-52)](https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-03-10_00-52.zip)
- Windows 10 **v1803 (OS Build 17134.345)**
- Crash dump generated by x32dbg.exe [dump-12032019_1626570634.zip](https://github.com/phiDelPark/x64DbgPlugins/files/2957374/dump-12032019_1626570634.zip)
pw: 123

This is just a minor bug, the plugin is perfectly functioning and does its job as intended, hoping to see more improvements for it.

**Comment by charygao** [comment]
I have the same issue too。[https://github.com/x64dbg/x64dbg/issues/2186](https://github.com/x64dbg/x64dbg/issues/2186)

**Comment by phiDelPark** [comment]
I don't use "QT" anymore, so I can't compile. sorry...
